---
- hosts: webserver
  become: yes
  become_user: root
  vars:
    - homeDir: /home/ubuntu
    - appDir : app
    - repo: rest-crud
    - account: codetrash

  tasks:
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - git
      - mcrypt
      - nginx
      - curl
      - mysql-server

  - name: Install pm2
    npm: name=pm2 global=yes production=yes

  - name: Create APP Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  - name: Git Clone Repo
    git: repo=https://github.com/{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} force=yes update=yes
    register: git_finished
  - name: pointing NodeJS app to mysql host
    replace: dest={{homeDir}}/{{appDir}}/server.js regexp='localhost'
      replace='{{ hostvars['db01']['ansible_eth0']['ipv4']['address'] }}'

  - name: pointing NodeJS app to mysql host
    replace: dest={{homeDir}}/{{appDir}}/server.js regexp=''''
      replace=''root''

  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}/
    register: npm_finished
    when: git_finished.changed

  - name: Stop APP
    command: pm2 stop app chdir={{homeDir}}/{{appDir}}
    ignore_errors: yes

  - name: Start APP
    command: pm2 start server.js --name app chdir={{homeDir}}/{{appDir}}
    ignore_errors: yes
#    when: npm_finished.changed
  
